<?php if ($cl['li']['advertising']): ?>
	<?php echo cl_template('timeline/ad'); ?>
<?php else: ?>
	<div class="post-list-item" data-list-item="<?php echo($cl['li']['id']); ?>" data-post-offset="<?php echo($cl['li']['offset_id']); ?>" <?php echo fetch_or_get($cl['li']['attrs'],''); ?>>
		<?php if (not_empty($cl['li']['me_blocked'])): ?>
			<div class="post-placeholder">
				<div class="d-flex flex-wn align-items-center">
					<div class="flex-item">
						<div class="icon">
							<?php echo cl_icon("blocked"); ?>
						</div>
					</div>
					<div class="felx-item">
						<p>
							<?php echo cl_translate("This user ({@uname@}) has blocked you from accessing their posts", array(
								"uname" => cl_html_el("a", $cl['li']['owner']['username'], array(
									"href" => $cl['li']['owner']['url'],
									"data-spa" => "true"
								))
							)); ?>
						</p>
					</div>
				</div>
			</div>
		<?php elseif (empty($cl['li']['can_see'])): ?>
			<div class="post-placeholder">
				<div class="d-flex flex-wn align-items-center">
					<div class="flex-item">
						<div class="icon">
							<?php echo cl_icon("visibility_off"); ?>
						</div>
					</div>
					<div class="felx-item">
						<p>
							<?php echo cl_translate("Only followers of this user ({@uname@}) can see their posts", array(
								"uname" => cl_html_el("a", $cl['li']['owner']['username'], array(
									"href" => $cl['li']['owner']['url'],
									"data-spa" => "true"
								))
							)); ?>
						</p>
					</div>
				</div>
			</div>
		<?php else: ?>
			<?php if (not_empty($cl['li']['is_repost'])): ?>
				<div class="post-list-item__header">
					<div class="publication-repost">
						<?php echo cl_icon('repeat'); ?>
						<?php if (not_empty($cl['li']['is_reposter'])): ?>
							<a href="<?php echo $me['url']; ?>" data-spa="true">
								<?php echo cl_translate('You reposted'); ?>
							</a>
						<?php else: ?>
							<a href="<?php echo($cl['li']['reposter']['url']); ?>" data-spa="true">
								<?php echo cl_translate('{@uname@} reposted', array('uname' => $cl['li']['reposter']['name'])) ?>
							</a>
						<?php endif; ?>
					</div>
				</div>
			<?php endif; ?>

			<div class="post-list-item__content">
				<div class="post-data">
					<div class="post-data__avatar">
						<a class="block-link" href="<?php echo($cl['li']['url']); ?>" data-spa="true">
							<div class="avatar-holder">
								<img class="lozad" data-src="<?php echo($cl['li']['owner']['avatar']); ?>">
							</div> 
						</a>
					</div>
					<div class="post-data__content">
						<?php if (not_empty($cl['li']['is_blocked'])): ?>
							<div class="post-data__content-hidden" data-softhidden-post="<?php echo($cl['li']['id']); ?>">
								<div class="soft-hidden-post">
									<div class="d-flex align-items-center flex-wn">
										<div class="flex-item flex-grow-1">
											<p><?php echo cl_translate('This is a message from the user you blocked'); ?></p>
										</div>
										<div class="flex-item">
											<button class="btn btn-custom main-outline sm" onclick="SMColibri.show_post(<?php echo($cl['li']['id']); ?>, 'blocked');">
												<?php echo cl_translate('View'); ?>
											</button>
										</div>	
									</div>
								</div>
							</div>
						<?php elseif(not_empty($cl['li']['is_reported'])): ?>
							<div class="post-data__content-hidden" data-softhidden-post="<?php echo($cl['li']['id']); ?>">
								<div class="soft-hidden-post">
									<div class="d-flex align-items-center flex-wn">
										<div class="flex-item flex-grow-1">
											<p>
												<?php echo cl_translate('This post is currently under review'); ?>	
											</p>
										</div>
										<div class="flex-item">
											<button class="btn btn-custom main-outline sm" onclick="SMColibri.show_post(<?php echo($cl['li']['id']); ?>, 'reported');">
												<?php echo cl_translate('View'); ?>
											</button>
										</div>	
									</div>
								</div>
							</div>
						<?php endif; ?>

						<div class="post-data__content-inner">
							<div class="post-data-layout">
								<div class="post-data-layout__publisher">
									<div class="post-username">
										<a href="<?php echo($cl['li']['owner']['url']); ?>" data-spa="true" data-uinfo-lbox="<?php echo($cl['li']['owner']['id']); ?>" data-toggle="popover" data-placement="bottom">
											<span class="user-name-holder">
												<span class="user-name-holder__name">
													<?php echo($cl['li']['owner']['name']); ?>
												</span>

												<?php if ($cl['li']['owner']['verified'] == '1'): ?>
													<span class="user-name-holder__badge">
														<?php echo cl_icon("verified_user_badge"); ?>
													</span>
												<?php endif; ?>
											</span>
											<span class="user-name-slug">
												@<?php echo($cl['li']['owner']['username']); ?>	
											</span>
										</a>
									</div>
									<div class="post-time">
										<?php echo($cl['li']['time']); ?>

										<?php if (not_empty($cl['li']['edited'])): ?>
											<span title="<?php echo cl_translate("Edited"); ?>: <?php echo cl_date("h:i A - M d, Y", $cl['li']['edited'], true); ?>">
												(E)
											</span>
										<?php endif; ?>
									</div>
								</div>
								<?php if ($cl['li']['target'] == 'pub_reply' && not_empty($cl['li']['reply_to'])): ?>
									<div class="post-data-layout__target">
										<?php if (not_empty($cl['li']['reply_to']['is_owner'])): ?>
											<div class="post-reply">
												<span>
													<?php echo cl_translate('In response to your {@post_url@}', array(
														'post_url' => cl_html_el('a', cl_translate('post'), array(
															'href' => $cl['li']['reply_to']['thread_url'],
															'data-spa' => 'true'
														))
													)); ?>
												</span>
											</div>
										<?php else: ?>
											<div class="post-reply">
												<span>
													<?php
														if ($cl['li']['reply_to']['gender'] == 'M') {
															$text_temp = 'In response {@uname@} to his {@post_url@}';
														}
														
														else if ($cl['li']['reply_to']['gender'] == 'F') {
															$text_temp = 'In response {@uname@} to her {@post_url@}';
														}

														else if (in_array($cl['li']['reply_to']['gender'], array("T", "O"))) {
															$text_temp = 'In response {@uname@} to their {@post_url@}';
														}

														echo cl_translate($text_temp, array(
															'uname' => cl_html_el('a', $cl['li']['reply_to']['name'], array(
																'href' => $cl['li']['reply_to']['url'],
																'data-spa' => 'true'
															)),
															'post_url' => cl_html_el('a', cl_translate('publication'), array(
																'href' => $cl['li']['reply_to']['thread_url'],
																'data-spa' => 'true'
															))
														)); 
													?>
												</span>
											</div>
										<?php endif; ?>
									</div>
								<?php endif; ?>

								<div class="post-data-layout__content">
									<?php if (not_empty($cl['li']['text'])): ?>
										<?php 
											$cl['li']['text'] = cl_rn2br($cl['li']['text']);
											$cl['li']['text'] = cl_strip_brs($cl['li']['text']);
										?>
										<div class="publication-text">
											<?php echo($cl['li']['text']); ?>
										</div>
									<?php endif; ?>

									<?php if ($cl['li']['type'] == 'image' && not_empty($cl['li']['media'])): ?>
										<?php if (count($cl['li']['media']) == 1): ?>
											<div class="lozad-media">
												<div class="publication-image">
													<a href="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" class="fbox-media">
														<img class="lozad" data-src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" alt="Picture">
													</a>
												</div>
											</div>
										<?php else: ?>
											<div class="publication-images-collage">
												<?php foreach ($cl['li']['media'] as $i => $row): ?>
													<a href="<?php echo cl_get_media($row['src']); ?>" class="fbox-media" data-fancybox="fbox-media-<?php echo($cl['li']['id']); ?>">
														<div class="image-collage-item">
															<div class="lozad-media">
																<div class="publication-image">
																	<img class="d-block w-100 lozad" data-src="<?php echo cl_get_media($row['x']['image_thumb']); ?>" alt="Image">
																</div>
															</div>
														</div>
													</a>
												<?php endforeach; ?>
											</div>
										<?php endif; ?>
									<?php elseif($cl['li']['type'] == 'video' && not_empty($cl['li']['media'])): ?>
										<div class="lozad-media">
											<div class="publication-image">
												<a href="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" class="fbox-media">
													<img class="lozad" src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['x']['poster_thumb'],'')); ?>" alt="Video">
													<div class="video-play-button">
														<span class="video-play-button__arrow">
															<?php echo cl_icon("play_arrow"); ?>
														</span>
													</div>
												</a>
										    </div>
										</div>
									<?php elseif($cl['li']['type'] == 'audio' && not_empty($cl['li']['media'])): ?>
										<div class="publication-audio">
											<audio controls preload="metadata">
										        <source src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" type="audio/mpeg">
										        <source src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" type="audio/wav">
										    </audio>
										</div>
									<?php elseif($cl['li']['type'] == 'gif' && not_empty($cl['li']['media'])): ?>
										<div class="lozad-media">
											<div class="publication-image">
												<a href="<?php echo fetch_or_get($cl['li']['media'][0]['src'],''); ?>" class="fbox-media">
													<img class="lozad" data-src="<?php echo fetch_or_get($cl['li']['media'][0]['src'],''); ?>" alt="GIF-Image">
												</a>
											</div>
										</div>
									<?php elseif($cl['li']['type'] == 'poll' && not_empty($cl['li']['poll'])): ?>
										<div class="publication-poll" data-post-poll="<?php echo($cl['li']['id']); ?>" data-status="<?php echo($cl['li']['poll']['has_voted']); ?>">
											<div class="publication-poll__inner">
												<?php foreach ($cl['li']['poll']['options'] as $i => $poll_data): ?>
													<div class="publication-poll__option" onclick="SMColibri.vote_poll(<?php echo($cl['li']['id']); ?>, <?php echo($i); ?>);" data-poll-option="<?php echo($i); ?>">
														<div class="bar-icon">
															<?php echo cl_icon("check_circle"); ?>
														</div>
														<div class="bar-text">
															<p>
																<?php echo $poll_data["option"]; ?>
															</p>
														</div>
														<div class="bar-num">
															<b>
																<?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
																	<?php echo $poll_data["percentage"]; ?>%
																<?php endif; ?>
															</b>
														</div>

														<?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
															<span class="bar-slider" style="width: <?php echo $poll_data["percentage"]; ?>%;"></span>
														<?php else: ?>
															<span class="bar-slider"></span>
														<?php endif; ?>
													</div>
												<?php endforeach; ?>
											</div>
										</div>
									<?php elseif(not_empty($cl['li']['og_data'])): ?>
										<?php if (not_empty($cl['li']['og_data']['video_embed'])): ?>
											<div class="publication-og">
												<div class="publication-og__inner embeded-iframe">
													<div class="publication-og__image">
														<div class="lozad-media">
															<a href="<?php echo($cl['li']['og_data']['video_embed']); ?>" class="fbox-media">
																<img class="lozad" data-src="<?php echo($cl['li']['og_data']['image']); ?>" alt="Video">
																<div class="video-play-button">
																	<span class="video-play-button__arrow">
																		<?php echo cl_icon("play_arrow"); ?>
																	</span>
																</div>
															</a>
														</div>
													</div>
													<div class="publication-og__description">
														<h5>
															<?php echo($cl['li']['og_data']['title']); ?>
														</h5>
														<?php if (not_empty($cl['li']['og_data']['description'])): ?>
															<p>
																<?php echo($cl['li']['og_data']['description']); ?>
															</p>
														<?php else: ?>
															<p>
																<a target="_blank" href="<?php echo($cl['li']['og_data']['video_embed']); ?>">
																	<?php echo($cl['li']['og_data']['video_embed']); ?>
																</a>
															</p>
														<?php endif; ?>
													</div>
												</div>
											</div>
										<?php else: ?>
											<div class="publication-og">
												<div class="publication-og__inner link" data-href="<?php echo($cl['li']['og_data']['url']); ?>">
													<?php if (not_empty($cl['li']['og_data']['image'])): ?>
														<div class="publication-og__image">
															<img src="<?php echo($cl['li']['og_data']['image']); ?>" alt="IMG">
														</div>
													<?php endif; ?>
													
													<div class="publication-og__description">
														<h5>
															<?php echo($cl['li']['og_data']['title']); ?>
														</h5>
														<p>
															<?php echo($cl['li']['og_data']['description']); ?>
														</p>
														<a href="<?php echo($cl['li']['og_data']['url']); ?>" target="_blank">
															<?php echo($cl['li']['og_data']['url']); ?>
														</a>
													</div>
												</div>
											</div>
										<?php endif; ?>
									<?php endif; ?>
								</div>

								<div class="post-data-layout__controls">
									<button class="ctrls-item">
										<a class="ctrls-item__inner-link" href="<?php echo $cl['li']['url']; ?>" data-spa="true">
											<span class="ctrls-item__icon">
												<?php echo cl_icon('post_reply'); ?>
											</span>
											<span class="num"><?php echo $cl['li']['replys_count']; ?></span>
										</a>
									</button>

									<?php if (empty($cl['li']['has_liked'])): ?>
										<button class="ctrls-item" onclick="SMColibri.like_post('<?php echo $cl['li']['id']; ?>', this);">
											<span class="ctrls-item__icon">
												<?php echo cl_icon('sentiment_satisfied'); ?>
											</span>
											<span class="num" data-an="likes-count">
												<?php echo $cl['li']['likes_count']; ?>
											</span>
										</button>
									<?php else: ?>
										<button class="ctrls-item liked" onclick="SMColibri.like_post('<?php echo $cl['li']['id']; ?>', this);">
											<span class="ctrls-item__icon">
												<?php echo cl_icon('sentiment_satisfied'); ?>
											</span>
											<span class="num" data-an="likes-count">
												<?php echo $cl['li']['likes_count']; ?>
											</span>
										</button>
									<?php endif; ?>
									
									<?php if (empty($cl['li']['has_reposted'])): ?>
										<button onclick="SMColibri.repost('<?php echo $cl['li']['id']; ?>', this);" class="ctrls-item" data-an="repost-ctrl">
											<span class="ctrls-item__icon">
												<?php echo cl_icon('repeat'); ?>
											</span>
											<span class="num" data-an="reposts-count">
												<?php echo $cl['li']['reposts_count']; ?>
											</span>
										</button>
									<?php else: ?>
										<button onclick="SMColibri.repost('<?php echo $cl['li']['id']; ?>', this);" class="ctrls-item reposted" data-an="repost-ctrl">
											<span class="ctrls-item__icon">
												<?php echo cl_icon('repeat'); ?>
											</span>
											<span class="num" data-an="reposts-count">
												<?php echo $cl['li']['reposts_count']; ?>
											</span>
										</button>
									<?php endif; ?>

									<button class="ctrls-item" onclick="SMColibri.share_post('<?php echo $cl['li']['url']; ?>','<?php echo urlencode($cl['li']['url']); ?>');">
										<span class="ctrls-item__icon">
											<?php echo cl_icon('ios_share'); ?>
										</span>
									</button>
									<button class="ctrls-item dropleft">
										<div class="dropdown-toggle ctrls-item__icon" data-toggle="dropdown">
											<?php echo cl_icon('more_horiz'); ?>
										</div>
										<div class="dropdown-menu dropdown-icons">
											<a class="dropdown-item" href="<?php echo $cl['li']['url']; ?>" data-spa="true">
												<span class="flex-item dropdown-item-icon">
													<?php echo cl_icon('wysiwyg'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Show thread'); ?>
												</span>
												<span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
													<?php echo cl_icon('navigate_next'); ?>
												</span>
											</a>
											<div class="dropdown-divider"></div>
											<?php if (not_empty($cl['li']['can_edit'])): ?>
												<a onclick="SMColibri.edit_post('<?php echo $cl['li']['id']; ?>');" class="dropdown-item" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_icon('edit_note'); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Edit post'); ?>
													</span>
													<span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
														<?php echo cl_icon('looks_one'); ?>
													</span>
												</a>
												<div class="dropdown-divider"></div>
											<?php endif; ?>
											<?php if (not_empty($cl['li']['can_delete'])): ?>
												<a onclick="SMColibri.delete_post('<?php echo $cl['li']['id']; ?>');" class="dropdown-item col-red" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_icon('delete'); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Delete'); ?>
													</span>
												</a>
												<div class="dropdown-divider"></div>
											<?php endif; ?>
											<a onclick="SMColibri.show_likes('<?php echo $cl['li']['id']; ?>');" class="dropdown-item" href="javascript:void(0);">
												<span class="flex-item dropdown-item-icon">
													<?php echo cl_icon('sentiment_satisfied'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Show likes'); ?>
												</span>
												<span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
													<?php echo cl_icon('list_custom'); ?>
												</span>
											</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="javascript:void(0);">
												<span class="flex-item dropdown-item-icon">
													<?php echo cl_icon('bookmark'); ?>
												</span>
												<span class="flex-item" onclick="SMColibri.bookmark_post('<?php echo $cl['li']['id']; ?>', this);">
													<?php echo ((empty($cl['li']['has_saved'])) ? cl_translate('Bookmark') : cl_translate('Unbookmark')); ?>
												</span>
											</a>
											<a data-clipboard-text="<?php echo($cl['li']['url']); ?>" class="dropdown-item clip-board-copy" href="javascript:void(0);">
												<span class="flex-item dropdown-item-icon">
													<?php echo cl_icon('content_copy'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Copy link'); ?>
												</span>
											</a>
											
											<?php if (empty($cl['li']['is_owner'])): ?>
												<div class="dropdown-divider"></div>
												<a onclick="SMColibri.report_post(<?php echo($cl['li']['id']); ?>);" class="dropdown-item" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_icon('flag'); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Report post'); ?>
													</span>
													<span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
														<?php echo cl_icon('info'); ?>
													</span>
												</a>
											<?php endif; ?>
											<div class="dropdown-divider"></div>
											<a onclick="SMColibri.share_post('<?php echo $cl['li']['url']; ?>','<?php echo urlencode($cl['li']['url']); ?>');" class="dropdown-item" href="javascript:void(0);">
												<span class="flex-item dropdown-item-icon">
													<?php echo cl_icon('ios_share'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Share'); ?>
												</span>
											</a>
										</div>
									</button>
								</div>
							</div>
						</div>	
					</div>
				</div>
			</div>
		<?php endif;?>
	</div>

	<?php if (not_empty($cl["gads_horiz"])): ?>
		<?php if (cl_show_feed_gad()): ?>
			<div class="cl-google-ads centered">
				<?php echo $cl["gads_horiz"]; ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>