<br>PRIVACY POLICY
<br><br>Your privacy is important to us, so FiyrTwit, a service provider based in the NL, has created the following Privacy Policy ("Policy") to let you know what information we collect when you visit our Site http://www.fiyrtwit.com ("Site"), why we collect it and how we use it.
The terms "You," "Your," "Yours" and "User" refer to the entity/person/organization using our Site.
When this Policy mentions "We", "Us," and "Our" it refers to FiyrTwit and its subsidiaries and affiliates.
This Privacy Policy is governed by our Terms of Services.
For any questions regarding this Policy or any requests regarding the processing of personal data, please contact us at info@fiyrtwit.com.
<br><br>1. INFORMATION WE COLLECT FROM YOU
We collect the information You provide to us and this information is necessary for the adequate performance of the contractual arrangement which is in place between You and us and allow us to comply with our legal obligations.
Account Signup Information. When You create the account, we ask You to provide the signup information, such as Email, Username, Surname, Name, Passwords.
Communications, Chats, Messaging. When you communicate with us through email or any other way, we collect information about your communication and any information You choose to provide or disclose. In order to answer your request, we may access information provided by email, chats, purchase history, etc.
Login information. We collect Login information if You are logging to our account with Authentication Data.
<br><br>2. INFORMATION WE COLLECT AUTOMATICALLY
When you use our Site or contact us directly we may collect information, including your personal information, about the way you act in our Site, the services You use and how You use them.
This information is necessary for the adequate performance of the contract between You and us, to enable us to comply with legal obligations and given our legitimate interest in being able to provide and improve the functionalities of the Site.
Log data and Device information. We automatically collect log data and device information when you access and use the Site, even if you have not created an Account or logged in. That information includes, among other things: Internet protocol (IP) addresses, Date/time stamp.
Tracking technologies and Cookies. We use Cookies. We also automatically collect information about device’s operating system, .
<br><br>3. THE WAY WE USE YOUR INFORMATION
<br>We process your information adhering to the general data processing principles.
<br>We may use the information we collect through our Site for a number of reasons, including to:
<br>to identify user
<br>to create account
<br>to create trusted environment
<br>to create statistics and analyze market
<br>to stay connected
<br>to improve services
<br>to ensure data security and prevent fraud
<br>to comply with applicable laws
<br>to request feedback
<br>to provide support
<br>to customize marketing
<br><br>We will normally collect personal information from you only where we have your consent to do so, where we need the personal information to perform a contract with you, or where the processing is in our legitimate business interests.
<br><br>4. HOW WE MAY SHARE YOUR INFORMATION
<br>We may share your information with third parties that we use to provide and support our Services:
<br>Invoicing and Billing company - PayPal
<br>Invoicing and Billing company - Stripe
<br>Social media and advertising - Google AdSense
<br>Analytics - Google Analytics
<br>Retargeting platforms - Facebook Custom Audience
<br>We may also disclose your information to third parties:
<br>where required by law or regulatory requirement, court order or other judicial authorization;
<br>in response to lawful requests by public authorities, including for the purposes of meeting national security and law enforcement requirements;
<br>in connection with the sale, transfer, merger, bankruptcy, restructuring or other reorganization of a business;
<br>to protect or defend our rights, interests or property, or that of third parties; (e) to investigate any wrongdoing in connection with our products and services;
<br>and to protect the vital interests of an individual.
<br><br>5. COOKIES
Cookies are small text files stored by your browser on your computer when you visit our Site. We use cookies to improve our Site and make it easier to use. Cookies permit us to recognize users and avoid repetitive requests for the same information.
Please check our Cookie Policy to find more information about cookies we use.
You may find more information about how to delete cookies, as well as the other useful information related to the use of the cookies, on the website http://www.allaboutcookies.org/.
<br><br>6. INFORMATION FROM MINORS
This site and our Services are not intended for or directed to persons under the age of 18. We do not knowingly collect or ask for information from minors. We do not knowingly allow minors to use our Site or Services.
We will delete any information we discover is collected from a minor. Please contact us using the contact details below if you believe we might have information about a minor.
<br><br>7. SENSITIVE INFORMATION
We do not collect sensitive information such as political opinions, religious or philosophical beliefs, racial or ethnic origin, genetic data, biometric data, health data or data related a sexual orientation.
Please do not send, upload, or provide us any sensitive data and contact us using the contact details below if you believe that we might have such information. We have a right to delete any information we believe it might contain sensitive data.
<br><br>8. PAYMENT INFORMATION
To order and use our services we may require you to provide certain financial information to facilitate the processing of payments. We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your Personal information is governed by their Privacy Policy. All payment data is stored by . You may find their privacy policy link(s) here: .
<br><br>9. THIRD PARTY LINKS
Our Site may have links to other websites. Please review their privacy policies to learn more about how they collect and use your personal data, because we do not control their policies and personal data processing practices.
<br><br>10. RETENTION
We retain your personal information to provide services to you and as otherwise necessary to comply with our legal obligation, resolve disputes, and enforce our agreements.
We will retain your personal information not longer than you keep your account, unless we are otherwise required by law or regulations to retain your personal information longer.
If you would like to stop us using your personal information, you shall request that we erase your personal information and close your Account. Please note that even after deletion of your account we may keep some of your information for tax, legal reporting and auditing obligations.
<br><br>11. SECURITY
We have implemented security measures designed to protect the personal information you share with us, including physical, electronic and procedural measures. Among other things, we regularly monitor our systems for possible vulnerabilities and attacks.
Regardless of the measures and efforts taken by us, the transmission of information via internet, email or text message is not completely secure. We do not guarantee the absolute protection and security of your personal information.
We therefore encourage you to avoid providing us or anyone with any sensitive information of which you believe its disclosure could cause you substantial or irreparable harm.
If you have any questions regarding the security of our Site or Services, you are welcome to contact us at info@fiyrtwit.com.
<br><br>12. YOUR RIGHTS
You are entitled to a range of rights regarding the protection of your personal information. Those rights are:
The right to access the information we have about you. If you wish to access your personal information that we collect, you can do so at any time by contacting us using the contact details provided below.
The right to rectify inaccurate information about you. You can correct, update or request deletion of your personal information by contacting us using the contact details provided below.
The right to object the processing. When we rely on your consent to process your personal information, you may withdraw consent at any time by contacting us using the contact details provided below. This will not affect the lawfulness of processing prior to the withdrawal of your consent.
The right to lodge a complaint. You can raise questions or complaints to the national Data Protection Agency in your country of residence in the event where your rights may have been infringed. However, we recommend attempting to reach a peaceful resolution of the possible dispute by contacting us first.
The right to erase any data concerning you. You may demand erasure of data without undue delay for legitimate reasons, e.g. where data is no longer necessary for the purposes it was collected, or where the data has been unlawfully processed.
13. APPLICATION OF POLICY
This Policy was created with the help of the Privacy Policy Generator from TermsHub and applies only to the services offered by our Company. Our Policy does not apply to services offered by other companies or individuals, including products or sites that may be displayed to you in search results, sites that may include our services or other sites linked from our Site or Services.
<br><br>14. AMENDMENTS
Our Policy may change from time to time. We will post any Policy changes on our Site and, if the changes are significant, we may consider providing a more explicit notice (including, for certain services, email notification of Policy changes).
<br><br>15. ACCEPTANCE OF THIS POLICY
We assume that all Users of this Site have carefully read this document and agree to its contents. If someone does not agree with this Policy, they should refrain from using our Site. We reserve the right to change our Policy at any time and inform by using the way as indicated in Section 14. Continued use of this Site implies acceptance of the revised Policy.
<br><br>16. FURTHER INFORMATION
If you have any further questions regarding the data we collect, or how we use it, then please feel free to contact us at the details as indicated above.